import type { FilterType, ReviewType } from "@/types/reviews.type";

export const worldwideReviewImg =
  "https://cdn.shopify.com/s/files/1/0917/5649/5191/files/Trustpilot_Score.png?v=1752349211";
export const authenBadge =
  "https://judgeme-public-images.imgix.net/judgeme/medals-v2-2025-rebranding/auth/diamond.svg?auto=format";

export const checkBadge =
  "https://judgeme-public-images.imgix.net/judgeme/logos/verified-checkmark.svg";

export const reviewsData: ReviewType[] = [
  // 5-STAR REVIEWS (88 total)
  {
    rating: 5,
    title: "This Made a Big Impact",
    content:
      "I honestly didn't expect much from a device like this, but I was wrong. Within 2 weeks, the skin on my legs looked noticeably tighter and more toned. I've tried scrubs, dry brushing, creams—you name it—but this actually made a big difference. It's simple to use and totally worth it.",
    name: "Anna Cunningham",
    email: "anna.c2@email.com",
    isVerified: true,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Smoother Skin in Just Weeks",
    content:
      "The change in my skin texture after one month is remarkable. My cellulite has reduced so much and I feel amazing in my clothes again. This supplement really delivers on its promises!",
    name: "Melissa R.",
    email: "melissa.r@email.com",
    isVerified: false,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "My Confidence Is Back",
    content:
      "I can't thank Sculptique enough. After struggling with cellulite for years, I finally found something that works. Five weeks in and the dimpling has faded dramatically. I feel confident and beautiful again!",
    name: "Courtney J.",
    email: "courtney.j@email.com",
    isVerified: true,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Absolutely Transformative",
    content:
      "This product has been absolutely transformative for my skin. The cellulite on my thighs has improved more in four weeks than it did in years of trying other solutions. I'm less bloated and my skin feels firmer. Highly effective!",
    name: "Vanessa K.",
    email: "vanessa.k@email.com",
    isVerified: false,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Finally Something That Works",
    content:
      "After trying countless creams and treatments, I'm amazed by the results. Within three weeks, I noticed my thighs looking smoother and the dimpling less visible. The bloating I used to struggle with is almost gone. Best decision I've made for my body this year.",
    name: "Sarah M.",
    email: "sarah.m@email.com",
    isVerified: true,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "My Legs Look Amazing",
    content:
      "I was skeptical at first, but now I'm a believer. The texture on my legs has improved so much, and I feel more confident wearing shorts again. My husband even noticed without me saying anything. Already on my second bottle!",
    name: "Jennifer L.",
    email: "jenn.l@email.com",
    isVerified: true,
    createdDate: "01/18/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Game Changer for Cellulite",
    content:
      "This product exceeded my expectations. I've been taking it for five weeks and the cellulite on my thighs has visibly reduced. My skin feels firmer and I'm less bloated overall. Simple to use and totally worth it.",
    name: "Amanda R.",
    email: "amanda.r@email.com",
    isVerified: false,
    createdDate: "01/17/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Actually Works From Inside",
    content:
      "Unlike all those topical products I wasted money on, this actually addresses the problem from within. After a month, my skin texture has improved dramatically and the puffiness around my stomach area is gone.",
    name: "Lisa K.",
    email: "lisa.k@email.com",
    isVerified: true,
    createdDate: "01/17/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "No More Hiding My Legs",
    content:
      "I used to feel so self-conscious about my legs. After six weeks with Sculptique, the difference is incredible. The orange peel texture has smoothed out significantly and I finally feel comfortable in my own skin again.",
    name: "Emily T.",
    email: "emily.t@email.com",
    isVerified: true,
    createdDate: "01/16/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Impressive Results",
    content:
      "I've tried dry brushing, massage tools, expensive creams—nothing worked like this. Within four weeks my thighs looked noticeably smoother. The natural ingredients give me peace of mind too. Highly recommend!",
    name: "Maria G.",
    email: "maria.g@email.com",
    isVerified: false,
    createdDate: "01/16/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Worth Every Penny",
    content:
      "I was hesitant to spend the money, but this has been worth every cent. My cellulite has reduced significantly and I feel less bloated. The best part is how easy it is—just one capsule a day!",
    name: "Rachel S.",
    email: "rachel.s@email.com",
    isVerified: true,
    createdDate: "01/15/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Confidence Restored",
    content:
      "After having kids, my body changed and I struggled with cellulite for years. This supplement has helped me regain my confidence. My skin is smoother, firmer, and I feel like myself again. Thank you Sculptique!",
    name: "Jessica W.",
    email: "jessica.w@email.com",
    isVerified: true,
    createdDate: "01/15/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Natural and Effective",
    content:
      "I love that this uses natural ingredients. After three weeks, the dimpling on my thighs is less noticeable and my jeans fit better. No weird side effects, just real results.",
    name: "Katie P.",
    email: "katie.p@email.com",
    isVerified: false,
    createdDate: "01/14/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Purchase This Year",
    content:
      "Sculptique has transformed my skin. The cellulite on my buttocks and thighs has dramatically improved. I'm on my third bottle and will continue using it. Friends keep asking what I'm doing differently!",
    name: "Nicole B.",
    email: "nicole.b@email.com",
    isVerified: true,
    createdDate: "01/14/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Really Does Work",
    content:
      "I was doubtful about supplements for cellulite, but decided to give it a shot. Four weeks in and I'm amazed. My skin texture has improved and the bloating I dealt with daily is practically gone.",
    name: "Sophia C.",
    email: "sophia.c@email.com",
    isVerified: true,
    createdDate: "01/13/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Smoother Skin in Weeks",
    content:
      "The results speak for themselves. After just over a month, my legs look so much better. The dimples have faded and my skin feels tighter. I'm recommending this to all my friends!",
    name: "Megan H.",
    email: "megan.h@email.com",
    isVerified: false,
    createdDate: "01/13/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Life Changing Product",
    content:
      "I've struggled with cellulite since my twenties and nothing helped until now. Sculptique has genuinely changed how I feel about my body. The improvement in my skin texture is remarkable.",
    name: "Ashley D.",
    email: "ashley.d@email.com",
    isVerified: true,
    createdDate: "01/12/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Incredible Transformation",
    content:
      "Five weeks in and the difference is night and day. My thighs are smoother, less puffy, and the cellulite has visibly decreased. This is the only product that's ever actually worked for me.",
    name: "Lauren F.",
    email: "lauren.f@email.com",
    isVerified: true,
    createdDate: "01/12/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "So Happy With Results",
    content:
      "After years of being self-conscious, I finally found something that works. The cellulite on my legs has improved tremendously and I feel confident wearing dresses again. Thank you!",
    name: "Olivia J.",
    email: "olivia.j@email.com",
    isVerified: false,
    createdDate: "01/11/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Effective and Simple",
    content:
      "No complicated routine, no messy creams. Just take the capsule daily and watch the results happen. My skin is smoother and firmer after one month. Absolutely love this product!",
    name: "Taylor M.",
    email: "taylor.m@email.com",
    isVerified: true,
    createdDate: "01/11/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Better Than Expected",
    content:
      "I didn't expect much, but Sculptique has blown me away. The cellulite reduction is real and I'm less bloated throughout the day. My clothes fit better and I feel great!",
    name: "Hannah V.",
    email: "hannah.v@email.com",
    isVerified: true,
    createdDate: "01/10/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Finally Wearing Shorts Again",
    content:
      "I avoided shorts for years because of cellulite. After six weeks with this supplement, I'm comfortable showing my legs again. The texture has improved so much and I'm thrilled with the results.",
    name: "Chloe N.",
    email: "chloe.n@email.com",
    isVerified: false,
    createdDate: "01/10/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Amazing Product",
    content:
      "This has been a game changer for my confidence. The dimpling on my thighs has significantly reduced and my skin looks healthier overall. I'm so glad I tried Sculptique!",
    name: "Grace L.",
    email: "grace.l@email.com",
    isVerified: true,
    createdDate: "01/09/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Works Like Magic",
    content:
      "Four weeks in and the cellulite on my legs is barely noticeable. My skin feels firmer and I'm less puffy everywhere. This is the real deal and I couldn't be happier!",
    name: "Madison K.",
    email: "madison.k@email.com",
    isVerified: true,
    createdDate: "01/09/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Highly Effective",
    content:
      "I've wasted so much money on products that didn't work. Sculptique is different. The results are visible and my skin texture has improved dramatically. Worth every dollar!",
    name: "Ella R.",
    email: "ella.r@email.com",
    isVerified: false,
    createdDate: "01/08/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Cellulite Solution",
    content:
      "After trying everything on the market, this is hands down the best solution I've found. My thighs are smoother, my skin is firmer, and I feel amazing. Already recommended it to my sister!",
    name: "Ava S.",
    email: "ava.s@email.com",
    isVerified: true,
    createdDate: "01/08/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Visible Improvement",
    content:
      "The improvement in my skin texture is undeniable. After five weeks, the cellulite on my buttocks and thighs has reduced significantly. I feel more confident and comfortable in my body.",
    name: "Lily P.",
    email: "lily.p@email.com",
    isVerified: true,
    createdDate: "01/07/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Love This Supplement",
    content:
      "Easy to take, natural ingredients, and real results. My cellulite has improved so much in just one month. I'm less bloated and my skin feels healthier. Couldn't ask for more!",
    name: "Zoe W.",
    email: "zoe.w@email.com",
    isVerified: false,
    createdDate: "01/07/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Fantastic Results",
    content:
      "I'm blown away by how well this works. The orange peel texture on my thighs has smoothed out dramatically and I feel so much better about my appearance. This product is a lifesaver!",
    name: "Natalie H.",
    email: "natalie.h@email.com",
    isVerified: true,
    createdDate: "01/06/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Actually Delivers Results",
    content:
      "Unlike other products that overpromise and underdeliver, Sculptique actually works. My cellulite has decreased noticeably and my skin is tighter. I'm on my second bottle and loving it!",
    name: "Samantha G.",
    email: "samantha.g@email.com",
    isVerified: true,
    createdDate: "01/06/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Skin Looks So Much Better",
    content:
      "The transformation in my skin texture is amazing. After a month of daily use, the cellulite on my legs is barely visible. I feel confident and beautiful again. Thank you Sculptique!",
    name: "Victoria B.",
    email: "victoria.b@email.com",
    isVerified: false,
    createdDate: "01/05/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "No More Dimples",
    content:
      "The dimpling that used to cover my thighs has faded so much. Four weeks in and I can see real progress. My skin feels smoother and I'm less self-conscious about my body.",
    name: "Brooklyn T.",
    email: "brooklyn.t@email.com",
    isVerified: true,
    createdDate: "01/05/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Perfect Solution",
    content:
      "This is exactly what I needed. Simple to use, natural ingredients, and visible results. The cellulite on my thighs has improved dramatically and I couldn't be more pleased!",
    name: "Addison M.",
    email: "addison.m@email.com",
    isVerified: true,
    createdDate: "01/04/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Remarkable Improvement",
    content:
      "I've seen such remarkable improvement in just five weeks. My skin texture is smoother, the cellulite has reduced, and I feel less bloated. This product really works!",
    name: "Aubrey C.",
    email: "aubrey.c@email.com",
    isVerified: false,
    createdDate: "01/04/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Cellulite Practically Gone",
    content:
      "After six weeks, the cellulite on my legs is practically gone. The difference is incredible and I'm so happy I found this product. It's changed how I feel about my body completely.",
    name: "Scarlett D.",
    email: "scarlett.d@email.com",
    isVerified: true,
    createdDate: "01/03/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Exceeded All Expectations",
    content:
      "I had low expectations but this product exceeded them all. My thighs are smoother, firmer, and the cellulite has visibly decreased. I'm telling everyone about Sculptique!",
    name: "Aria F.",
    email: "aria.f@email.com",
    isVerified: true,
    createdDate: "01/03/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Feel Like a New Person",
    content:
      "This supplement has made me feel like a new person. The cellulite that plagued me for years has improved so much. My skin is smoother and I'm more confident than ever.",
    name: "Penelope J.",
    email: "penelope.j@email.com",
    isVerified: false,
    createdDate: "01/02/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Investment",
    content:
      "Investing in Sculptique was the best decision I made for my health and confidence. The results are real and my cellulite has decreased significantly. Absolutely worth it!",
    name: "Layla V.",
    email: "layla.v@email.com",
    isVerified: true,
    createdDate: "01/02/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Really Impressed",
    content:
      "I'm really impressed with how effective this is. After one month, my skin texture has improved dramatically and the bloating I dealt with is gone. Simple and effective!",
    name: "Riley K.",
    email: "riley.k@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Confidence Boost",
    content:
      "Sculptique has given me such a confidence boost. My cellulite has reduced noticeably and I feel comfortable in my skin again. The natural ingredients are a bonus too!",
    name: "Zoey N.",
    email: "zoey.n@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Genuinely Works",
    content:
      "This genuinely works and I'm so glad I gave it a try. The cellulite on my thighs has faded and my skin feels healthier. Already on my third bottle and seeing continuous improvement!",
    name: "Nora L.",
    email: "nora.l@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Life Changing",
    content:
      "I'm not exaggerating when I say this is life changing. My cellulite has improved so much in just a few weeks. I feel beautiful and confident again. Thank you so much!",
    name: "Stella R.",
    email: "stella.r@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Thrilled With Results",
    content:
      "I'm absolutely thrilled with my results. The dimpling on my thighs has smoothed out significantly and I'm less bloated overall. This product is amazing!",
    name: "Hazel S.",
    email: "hazel.s@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Works Wonders",
    content:
      "Sculptique works wonders for cellulite. After five weeks, my skin is noticeably smoother and firmer. I'm so happy I found this product and will continue using it!",
    name: "Violet P.",
    email: "violet.p@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Exactly What I Needed",
    content:
      "This is exactly what I needed to tackle my cellulite. The results are visible and I feel so much better about my body. Simple, effective, and totally worth it!",
    name: "Aurora W.",
    email: "aurora.w@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Amazing Experience",
    content:
      "My experience with Sculptique has been amazing. The cellulite on my legs has reduced dramatically and my skin feels tighter. I'm more confident and comfortable than I've been in years!",
    name: "Savannah H.",
    email: "savannah.h@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Highly Recommend",
    content:
      "I highly recommend this to anyone struggling with cellulite. The improvement in my skin texture is remarkable and I'm less bloated too. Great product!",
    name: "Brooklyn G.",
    email: "brooklyng@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Visible Changes",
    content:
      "The visible changes in my skin after just four weeks are incredible. My cellulite has decreased and my thighs look smoother. I'm so glad I tried Sculptique!",
    name: "Bella B.",
    email: "bella.b@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Perfect for Cellulite",
    content:
      "This is perfect for anyone dealing with stubborn cellulite. After one month, my skin is noticeably smoother and I feel so much better. Absolutely love this supplement!",
    name: "Claire T.",
    email: "claire.t@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Outstanding Product",
    content:
      "Outstanding product with real results. My cellulite has improved significantly and I'm less self-conscious about my legs. The natural formula is a huge plus too!",
    name: "Lucy M.",
    email: "lucy.m@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Skin Looks Incredible",
    content:
      "My skin looks incredible after five weeks of using Sculptique. The cellulite has faded so much and I feel confident wearing anything I want. This product is a miracle!",
    name: "Anna C.",
    email: "anna.c@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Better Than Creams",
    content:
      "So much better than any cream or topical treatment I've tried. This works from within and the results are lasting. My cellulite has decreased dramatically!",
    name: "Caroline D.",
    email: "caroline.d@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "So Effective",
    content:
      "I can't believe how effective this is. After just one month, my thighs are smoother and the dimpling has faded. I'm recommending Sculptique to everyone I know!",
    name: "Maya F.",
    email: "maya.f@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Changed My Life",
    content:
      "This product has genuinely changed my life. I struggled with cellulite for so long and nothing worked until Sculptique. My skin is smoother and I'm so much happier!",
    name: "Evelyn J.",
    email: "evelyn.j@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Real Results",
    content:
      "Real, visible results in just a few weeks. My cellulite has improved tremendously and I feel less bloated. This is the best supplement I've ever used!",
    name: "Ruby V.",
    email: "ruby.v@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Absolutely Wonderful",
    content:
      "Absolutely wonderful product! The cellulite on my legs has reduced so much and my skin feels firmer. I'm more confident and comfortable in my body now!",
    name: "Skylar K.",
    email: "skylar.k@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Impressive Formula",
    content:
      "The formula is impressive and the results speak for themselves. My skin texture has improved dramatically and the cellulite has faded. Highly effective!",
    name: "Ellie N.",
    email: "ellie.n@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Worth the Investment",
    content:
      "Definitely worth the investment. My cellulite has decreased significantly after six weeks and I feel so much better about my appearance. Great product!",
    name: "Ivy L.",
    email: "ivy.l@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Fantastic Supplement",
    content:
      "A fantastic supplement that actually works. My thighs are smoother, the cellulite has reduced, and I'm less bloated. I couldn't be happier with these results!",
    name: "Piper R.",
    email: "piper.r@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Exceeded Hopes",
    content:
      "This exceeded all my hopes. The cellulite that bothered me for years has improved so much in just one month. My skin looks and feels amazing!",
    name: "Nova S.",
    email: "nova.s@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Simple and Powerful",
    content:
      "Simple to use but powerful in results. The cellulite on my buttocks and thighs has visibly decreased and I feel more confident than ever. Love this!",
    name: "Willow P.",
    email: "willow.p@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Thing Ever",
    content:
      "This is the best thing I've ever tried for cellulite. After five weeks, my skin is noticeably smoother and firmer. I'm so grateful I found Sculptique!",
    name: "Elena W.",
    email: "elena.w@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Truly Effective",
    content:
      "Truly effective and worth every penny. My cellulite has improved dramatically and I'm less self-conscious about my body. This product is a winner!",
    name: "Genesis H.",
    email: "genesis.h@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Love the Results",
    content:
      "I love the results I'm seeing. The dimpling on my thighs has faded so much and my skin feels healthier. Already recommended it to my best friend!",
    name: "Quinn G.",
    email: "quinn.g@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Works Like Promised",
    content:
      "It works exactly like it promises. My cellulite has decreased noticeably and I'm less bloated. The natural ingredients make me feel good about taking it daily!",
    name: "Jade B.",
    email: "jade.b@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Product",
    content:
      "The best product I've used for cellulite reduction. After four weeks, my skin texture has improved tremendously and I feel so much more confident!",
    name: "Sienna T.",
    email: "sienna.t@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Wonderful Experience",
    content:
      "I've had a wonderful experience with Sculptique. The cellulite on my legs has reduced significantly and I'm thrilled with how my skin looks now!",
    name: "Ariana M.",
    email: "ariana.m@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Totally Recommend",
    content:
      "I totally recommend this to anyone struggling with cellulite. The improvement in my skin after one month is remarkable. Great product!",
    name: "Paisley C.",
    email: "paisley.c@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Great Investment",
    content:
      "Great investment for anyone dealing with stubborn cellulite. My thighs are smoother and I'm less bloated. Couldn't ask for better results!",
    name: "Kennedy D.",
    email: "kennedy.d@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Amazing Transformation",
    content:
      "The transformation in my skin has been amazing. After six weeks, the cellulite is barely visible and I feel beautiful again. Thank you Sculptique!",
    name: "Delilah F.",
    email: "delilah.f@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "So Happy",
    content:
      "I'm so happy with my results. The cellulite on my buttocks and thighs has decreased dramatically and my skin feels firmer. This product really works!",
    name: "Kinsley J.",
    email: "kinsley.j@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Perfect Product",
    content:
      "Perfect product for cellulite reduction. After five weeks, my skin is noticeably smoother and I'm more confident. I'll definitely continue using this!",
    name: "Adalyn V.",
    email: "adalyn.v@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Exceptional Results",
    content:
      "Exceptional results in just one month. The cellulite has faded so much and my skin feels healthier. This is the real deal!",
    name: "Naomi K.",
    email: "naomi.k@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Miracle Supplement",
    content:
      "This is a miracle supplement. My thighs look amazing after six weeks and the cellulite is practically gone. I'm so grateful for this product!",
    name: "Emilia N.",
    email: "emilia.n@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Couldn't Be Happier",
    content:
      "I couldn't be happier with these results. The dimpling on my legs has smoothed out and I feel confident again. Sculptique is amazing!",
    name: "Valentina L.",
    email: "valentina.l@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Best Decision",
    content:
      "Best decision I've made this year. My cellulite has decreased significantly and my skin texture has improved dramatically. Worth every cent!",
    name: "Athena R.",
    email: "athena.r@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Truly Amazing",
    content:
      "Truly amazing product. After four weeks, my skin is smoother and firmer. The cellulite on my thighs has visibly reduced. I'm so impressed!",
    name: "Iris S.",
    email: "iris.s@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Works Perfectly",
    content:
      "Works perfectly for stubborn cellulite. My skin looks so much better after just five weeks and I'm less bloated too. Highly recommend!",
    name: "Alaina P.",
    email: "alaina.p@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Phenomenal Product",
    content:
      "Phenomenal product with real, lasting results. The cellulite on my legs has improved tremendously and I feel beautiful again. Thank you!",
    name: "Camila W.",
    email: "camila.w@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Absolutely Love It",
    content:
      "I absolutely love this supplement. My cellulite has decreased so much in just one month and my skin feels amazing. Already on my second bottle!",
    name: "Rylee H.",
    email: "rylee.h@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Skin Feels Great",
    content:
      "My skin feels great after using Sculptique. The cellulite has faded noticeably and I'm more confident wearing swimsuits. This product is incredible!",
    name: "Eliana G.",
    email: "eliana.g@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Superb Results",
    content:
      "Superb results after six weeks. My thighs are smoother, the dimpling has reduced, and I feel so much better. This is the best cellulite solution!",
    name: "Raelynn B.",
    email: "raelynn.b@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Five Stars",
    content:
      "Five stars all the way! The cellulite on my legs has improved dramatically and my skin texture is so much better. Absolutely worth it!",
    name: "Mackenzie T.",
    email: "mackenzie.t@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 5,
    title: "Outstanding Results",
    content:
      "Outstanding results in just four weeks. My skin is smoother, firmer, and the cellulite has visibly decreased. I'm thrilled with this product!",
    name: "Josie M.",
    email: "josie.m@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },

  // 4-STAR REVIEWS (17 total)
  {
    rating: 4,
    title: "Good Results So Far",
    content:
      "I've been using this for three weeks and I'm seeing some improvement in my cellulite. The texture is getting better but I think I need more time to see the full results. Overall pleased with it.",
    name: "Michelle A.",
    email: "michelle.a@email.com",
    isVerified: true,
    createdDate: "01/17/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Working Well",
    content:
      "It's working well but the results are gradual. After four weeks, I can see some reduction in cellulite but not as dramatic as I hoped. Still, it's better than anything else I've tried.",
    name: "Christine P.",
    email: "christine.p@email.com",
    isVerified: false,
    createdDate: "01/15/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Decent Product",
    content:
      "Decent product overall. I've noticed some improvement in my skin texture after a month. The cellulite is still there but less noticeable. Will continue and see if it gets better.",
    name: "Stephanie R.",
    email: "stephanie.r@email.com",
    isVerified: true,
    createdDate: "01/13/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Seeing Some Changes",
    content:
      "Seeing some changes in my cellulite after five weeks. My skin feels smoother but the dimpling is still visible in certain lighting. It's helping but takes patience.",
    name: "Angela K.",
    email: "angela.k@email.com",
    isVerified: false,
    createdDate: "01/11/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Pretty Good",
    content:
      "Pretty good supplement. The cellulite has improved somewhat and I'm less bloated. I was hoping for faster results but it's definitely working. Will keep using it.",
    name: "Deborah L.",
    email: "deborah.l@email.com",
    isVerified: true,
    createdDate: "01/09/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Helpful But Slow",
    content:
      "It's helpful but the progress is slower than expected. After six weeks, there's definite improvement in my skin texture but I thought it would be more dramatic by now.",
    name: "Patricia M.",
    email: "patricia.m@email.com",
    isVerified: false,
    createdDate: "01/07/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Good Not Great",
    content:
      "Good but not great. I can see some reduction in cellulite after a month but it's subtle. My skin does feel better though and I'm less puffy overall.",
    name: "Sandra H.",
    email: "sandra.h@email.com",
    isVerified: true,
    createdDate: "01/06/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Making Progress",
    content:
      "I'm making progress with this supplement. The cellulite is improving but it takes time. After four weeks, I'd say it's reduced by maybe 30%. Happy to continue.",
    name: "Donna W.",
    email: "donna.w@email.com",
    isVerified: false,
    createdDate: "01/05/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Works But Takes Time",
    content:
      "It works but you need to be patient. I'm on week five and seeing gradual improvement. The cellulite is less noticeable but still there. Worth continuing with.",
    name: "Carol G.",
    email: "carol.g@email.com",
    isVerified: true,
    createdDate: "01/04/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Satisfied Overall",
    content:
      "I'm satisfied overall with the results. My skin texture has improved and the bloating is better. The cellulite reduction is moderate but noticeable enough.",
    name: "Nancy B.",
    email: "nancy.b@email.com",
    isVerified: false,
    createdDate: "01/03/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Solid Product",
    content:
      "Solid product that does help with cellulite. After a month, I can see some improvement but I expected more dramatic changes. Still, it's better than nothing.",
    name: "Karen T.",
    email: "karen.t@email.com",
    isVerified: true,
    createdDate: "01/02/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Gradual Improvement",
    content:
      "Gradual improvement in my cellulite over six weeks. It's not a miracle cure but it does help. My skin feels smoother and I'm less self-conscious.",
    name: "Betty J.",
    email: "betty.j@email.com",
    isVerified: false,
    createdDate: "01/02/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Does Help",
    content:
      "It does help reduce cellulite but don't expect overnight results. After five weeks, there's noticeable improvement but it's not dramatic. Good supplement though.",
    name: "Helen V.",
    email: "helen.v@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Reasonable Results",
    content:
      "Reasonable results after a month of use. The cellulite has improved a bit and my skin texture is better. I think with more time it'll get even better.",
    name: "Dorothy N.",
    email: "dorothy.n@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Moderately Effective",
    content:
      "Moderately effective for cellulite reduction. I've been using it for four weeks and can see some changes. Not as fast as I'd like but it's working.",
    name: "Sharon F.",
    email: "sharon.f@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Some Improvement",
    content:
      "Some improvement in my cellulite after three weeks. It's subtle but my skin does feel better. I'll continue using it and hope for more visible results.",
    name: "Ruth D.",
    email: "ruth.d@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },
  {
    rating: 4,
    title: "Worth Trying",
    content:
      "Worth trying if you have cellulite. I've noticed some reduction after five weeks but it's gradual. The bloating reduction is nice too. Overall a good product.",
    name: "Margaret S.",
    email: "margaret.s@email.com",
    isVerified: true,
    createdDate: "01/01/2025",
    urls: [],
  },

  // 3-STAR REVIEWS (8 total)
  {
    rating: 3,
    title: "Okay Results",
    content:
      "Results are okay but not amazing. I've been using this for a month and there's minimal change in my cellulite. Maybe I need to give it more time.",
    name: "Linda C.",
    email: "linda.c@email.com",
    isVerified: true,
    createdDate: "01/14/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Average Product",
    content:
      "Average product in my experience. After four weeks, I can't really see much difference in my cellulite. It might work for others but not seeing much for me yet.",
    name: "Barbara M.",
    email: "barbara.m@email.com",
    isVerified: false,
    createdDate: "01/12/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Not Sure Yet",
    content:
      "I'm not sure yet if this is working. Three weeks in and I don't see much change. Maybe it needs more time but I was expecting faster results.",
    name: "Susan L.",
    email: "susan.l@email.com",
    isVerified: true,
    createdDate: "01/10/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Minimal Changes",
    content:
      "Minimal changes after five weeks. I do feel less bloated but the cellulite looks about the same. It's not bad but not the miracle I was hoping for.",
    name: "Jessica H.",
    email: "jessica.h2@email.com",
    isVerified: false,
    createdDate: "01/08/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Mixed Feelings",
    content:
      "I have mixed feelings about this. Some days I think I see improvement, other days not so much. After a month, the results are underwhelming.",
    name: "Sarah K.",
    email: "sarah.k2@email.com",
    isVerified: true,
    createdDate: "01/06/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Slightly Helpful",
    content:
      "Slightly helpful but not as effective as I hoped. Been using it for six weeks and the cellulite is maybe a tiny bit better. Expected more for the price.",
    name: "Lisa R.",
    email: "lisa.r2@email.com",
    isVerified: false,
    createdDate: "01/04/2025",
    urls: [
      {
        type: "image",
        url: "https://judgeme.imgix.net/sculptique/1752663679__1752663592120-image__original.jpg?auto=format&w=1024",
      },
      {
        type: "image",
        url: "https://judgeme.imgix.net/sculptique/1752663682__1752663674935-image__original.jpg?auto=format&w=1024",
      },
    ],
  },
  {
    rating: 3,
    title: "Underwhelming",
    content:
      "Pretty underwhelming results. After four weeks, I don't see much change in my cellulite. It's possible it needs more time but I'm not impressed so far.",
    name: "Jennifer P.",
    email: "jennifer.p@email.com",
    isVerified: true,
    createdDate: "01/02/2025",
    urls: [],
  },
  {
    rating: 3,
    title: "Neutral Experience",
    content:
      "Neutral experience overall. I've been taking it for a month and haven't noticed significant changes. Maybe it works better for some people than others.",
    name: "Amy W.",
    email: "amy.w@email.com",
    isVerified: false,
    createdDate: "01/01/2025",
    urls: [],
  },

  // 2-STAR REVIEW (1 total)
  {
    rating: 2,
    title: "Disappointed",
    content:
      "I'm disappointed with the results. After six weeks, I barely see any difference in my cellulite. The product might work for others but it hasn't done much for me. Not sure if I'll continue.",
    name: "Mary T.",
    email: "mary.t@email.com",
    isVerified: true,
    createdDate: "01/03/2025",
    urls: [],
  },
];

export const filterTypeData: FilterType[] = [
  { value: "most-recent", label: "Most Recent", type: "sort" },
  { value: "highest-rating", label: "Highest Rating", type: "sort" },
  { value: "lowest-rating", label: "Lowest Rating", type: "sort" },
  { value: "only-pictures", label: "Only Pictures", type: "filter" },
  { value: "pictures-first", label: "Pictures First", type: "sort" },
  { value: "videos-first", label: "Videos First", type: "sort" },
  { value: "most-helpful", label: "Most Helpful", type: "sort" },
];

export const displayNameData = [
  "John Smith",
  "John S.",
  "John",
  "J.S",
  "Anonymous",
];
